# Word embedding Techniques using Embedding Layer in Keras 

In [1]:
#### Libraries used Tenserflow > 2.0 in Keras

In [2]:
import warnings
warnings.filterwarnings('ignore')
# ! pip install tenserflow-gpu

In [8]:
# !pip install tensorflow
! pip install tensorflow-gpu

Defaulting to user installation because normal site-packages is not writeable
  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [44 lines of output]
  Traceback (most recent call last):
    File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 35, in __init__
      parsed = _parse_requirement(requirement_string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 64, in parse_requirement
      return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 82, in _parse_requirement
      url, specifier, marker = _parse_requirement_details(tokenizer)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\ProgramData\anaconda3\Lib\site-packages\setuptools\_v

In [10]:
import tensorflow as tf
print(tf.__version__)


2.15.0


In [12]:
### tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
#### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good'] 

In [14]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [15]:
#### Vocubulary size
voc_size = 500

# One Hot Representation

In [16]:
onehot_rep = [one_hot(words,voc_size) for words in sent]
print(onehot_rep)

[[9, 91, 285, 52], [9, 91, 285, 170], [9, 308, 285, 308], [429, 452, 385, 213, 432], [429, 452, 385, 213, 465], [311, 9, 318, 285, 247], [398, 390, 346, 213]]


# Word Embedding Representation

In [20]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [21]:
import numpy as np

In [26]:
## pre padding
sent_length = 8
embedded_docs = pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0   9  91 285  52]
 [  0   0   0   0   9  91 285 170]
 [  0   0   0   0   9 308 285 308]
 [  0   0   0 429 452 385 213 432]
 [  0   0   0 429 452 385 213 465]
 [  0   0   0 311   9 318 285 247]
 [  0   0   0   0 398 390 346 213]]


In [27]:
## 10 feature dimensions
dim = 10

In [29]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [33]:
## 'the glass of milk'
embedded_docs[0]

array([  0,   0,   0,   0,   9,  91, 285,  52])

In [34]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 84ms/step


array([[-8.3014369e-03,  2.7044203e-02, -1.9349743e-02, -1.5992604e-02,
         3.1605843e-02, -5.7291240e-05,  2.1477286e-02, -3.7638210e-02,
         2.6229236e-02,  3.9304856e-02],
       [-8.3014369e-03,  2.7044203e-02, -1.9349743e-02, -1.5992604e-02,
         3.1605843e-02, -5.7291240e-05,  2.1477286e-02, -3.7638210e-02,
         2.6229236e-02,  3.9304856e-02],
       [-8.3014369e-03,  2.7044203e-02, -1.9349743e-02, -1.5992604e-02,
         3.1605843e-02, -5.7291240e-05,  2.1477286e-02, -3.7638210e-02,
         2.6229236e-02,  3.9304856e-02],
       [-8.3014369e-03,  2.7044203e-02, -1.9349743e-02, -1.5992604e-02,
         3.1605843e-02, -5.7291240e-05,  2.1477286e-02, -3.7638210e-02,
         2.6229236e-02,  3.9304856e-02],
       [-3.9549530e-02,  1.1617161e-02,  2.5027778e-02, -2.4874795e-02,
         4.2937126e-02, -1.2492910e-03,  8.6935535e-03,  2.8109420e-02,
         8.5973367e-03,  4.8006270e-02],
       [-2.2751272e-02,  2.2150468e-02, -3.6828946e-02, -2.3860371e-02,
   

In [35]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 44ms/step
[[[-8.30143690e-03  2.70442031e-02 -1.93497427e-02 -1.59926042e-02
    3.16058435e-02 -5.72912395e-05  2.14772858e-02 -3.76382098e-02
    2.62292363e-02  3.93048562e-02]
  [-8.30143690e-03  2.70442031e-02 -1.93497427e-02 -1.59926042e-02
    3.16058435e-02 -5.72912395e-05  2.14772858e-02 -3.76382098e-02
    2.62292363e-02  3.93048562e-02]
  [-8.30143690e-03  2.70442031e-02 -1.93497427e-02 -1.59926042e-02
    3.16058435e-02 -5.72912395e-05  2.14772858e-02 -3.76382098e-02
    2.62292363e-02  3.93048562e-02]
  [-8.30143690e-03  2.70442031e-02 -1.93497427e-02 -1.59926042e-02
    3.16058435e-02 -5.72912395e-05  2.14772858e-02 -3.76382098e-02
    2.62292363e-02  3.93048562e-02]
  [-3.95495296e-02  1.16171613e-02  2.50277780e-02 -2.48747952e-02
    4.29371260e-02 -1.24929100e-03  8.69355351e-03  2.81094201e-02
    8.59733671e-03  4.80062701e-02]
  [-2.27512717e-02  2.21504681e-02 -3.68289463e-02 -2.38603707e-02
   -4.39352766e-02  1.55094974e

In [36]:
embedded_docs[0]

array([  0,   0,   0,   0,   9,  91, 285,  52])

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]