In [20]:
import tensorflow as tf
# print(tf.__version__)

In [21]:
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
#### sentences
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [23]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [24]:
#### vocubulary size
voc_size = 500

# One Hot Representation

In [25]:
onehot_res = [one_hot(words,voc_size) for words in sent]
onehot_res

[[454, 264, 349, 111, 194, 245],
 [436, 367, 349, 62, 68, 396],
 [416, 238, 82, 372],
 [454, 208, 349, 87, 454, 297],
 [239, 390, 498, 349, 62, 68, 396],
 [423, 349, 62, 68, 24, 433]]

# Word Embedding Representation

In [26]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [27]:
import numpy as np

In [28]:
## prepadding
sent_length = 8
embedded_docs = pad_sequences(onehot_res,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0 454 264 349 111 194 245]
 [  0   0 436 367 349  62  68 396]
 [  0   0   0   0 416 238  82 372]
 [  0   0 454 208 349  87 454 297]
 [  0 239 390 498 349  62  68 396]
 [  0   0 423 349  62  68  24 433]]


In [29]:
## 10 feature dimensions
dim = 10

In [30]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [31]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [32]:
## 'The world is a better place'
embedded_docs[0]

array([  0,   0, 454, 264, 349, 111, 194, 245])

In [33]:
print(model.predict(embedded_docs[0]))

1/1 [==============================] - 0s 45ms/step
[[ 0.01957956  0.0435085   0.00912322  0.04572562  0.03584453  0.0244208
  -0.02145196 -0.03818391  0.01192585  0.00257744]
 [ 0.01957956  0.0435085   0.00912322  0.04572562  0.03584453  0.0244208
  -0.02145196 -0.03818391  0.01192585  0.00257744]
 [-0.01507466 -0.03089141  0.01244392  0.03266069  0.00618977 -0.01361569
   0.04422916 -0.02898675 -0.04096063  0.03094826]
 [ 0.00697607 -0.02183778  0.02112234  0.02223383  0.01006684 -0.01379486
   0.04244718 -0.012852   -0.01935415  0.04991398]
 [ 0.01022596 -0.00223    -0.00395475 -0.04742975 -0.02258097  0.01430656
  -0.01645232 -0.03282805 -0.01049179 -0.00405073]
 [ 0.03557259  0.019025    0.01802126 -0.02991667  0.04858769 -0.04907061
   0.02661267  0.04020769 -0.04647261  0.03522107]
 [-0.04611126  0.03658127  0.00929661  0.04621654  0.04701335  0.00378732
   0.00222442 -0.03325278  0.01169875 -0.03562545]
 [-0.0232056   0.01301574 -0.01615524  0.01082623  0.00571573  0.04308898
 

In [34]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 39ms/step
[[[ 0.01957956  0.0435085   0.00912322  0.04572562  0.03584453
    0.0244208  -0.02145196 -0.03818391  0.01192585  0.00257744]
  [ 0.01957956  0.0435085   0.00912322  0.04572562  0.03584453
    0.0244208  -0.02145196 -0.03818391  0.01192585  0.00257744]
  [-0.01507466 -0.03089141  0.01244392  0.03266069  0.00618977
   -0.01361569  0.04422916 -0.02898675 -0.04096063  0.03094826]
  [ 0.00697607 -0.02183778  0.02112234  0.02223383  0.01006684
   -0.01379486  0.04244718 -0.012852   -0.01935415  0.04991398]
  [ 0.01022596 -0.00223    -0.00395475 -0.04742975 -0.02258097
    0.01430656 -0.01645232 -0.03282805 -0.01049179 -0.00405073]
  [ 0.03557259  0.019025    0.01802126 -0.02991667  0.04858769
   -0.04907061  0.02661267  0.04020769 -0.04647261  0.03522107]
  [-0.04611126  0.03658127  0.00929661  0.04621654  0.04701335
    0.00378732  0.00222442 -0.03325278  0.01169875 -0.03562545]
  [-0.0232056   0.01301574 -0.01615524  0.01082623  0.00571

In [35]:
embedded_docs[0]

array([  0,   0, 454, 264, 349, 111, 194, 245])